# Generated by Django 4.2.20 on 2025-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubLinkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'sub_link_user',
                'ordering': ['-id'],
                'unique_together': {('telegram_id', 'username')},
            },
        ),
    ]
