# Dockerfile-cron

FROM python:3.9-alpine

# Install system & cron dependencies
RUN apk add --no-cache \
    build-base \
    mariadb-dev \
    nodejs \
    npm \
    curl \
    bash \
    git \
    tzdata \
    postgresql-dev \
    libffi-dev \
    openssl-dev \
    py3-pip \
    && pip install --upgrade pip

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

# Install Python and JS dependencies
RUN pip install -r requirements.txt
WORKDIR /app/theme/static_src
RUN npm install && npm run build

# Set back to app root
WORKDIR /app

# Set up crontab to run every 30 minutes
RUN echo "*/5 * * * * cd /app && python manage.py sync_and_update_links >> /var/log/cron.log 2>&1" > /etc/crontabs/root

# Start cron
CMD ["crond", "-f", "-l", "8"]